#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.8.1 on Wed Jul 11 04:59:13 2018
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class TemplateExporter(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: TemplateExporter.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.p1 = wx.Panel(self, wx.ID_ANY)
        self.Filetype = wx.ComboBox(self.p1, 01, choices=["PNG, 16bit, Grayscale", "PNG, 8bit, Grayscale", "TIFF, 16bit, Grayscale", "TIFF, 8bit, Grayscale", "TIFF Stack, 16bit, Grayscale", "TIFF Stack, 8bit, Grayscale", "NUMPY, 32bit, uint (npy)", "NUMPY, 32bit, uint (npz)", "HDF, 64bit, int, 'stack'"], style=wx.CB_DROPDOWN)
        self.Filename = wx.TextCtrl(self.p1, 02, "")
        self.StartID = wx.SpinCtrl(self.p1, 03, "0", min=0, max=100000)
        self.NumDigits = wx.SpinCtrl(self.p1, 04, "4", min=4, max=8)
        self.p2 = wx.Panel(self, wx.ID_ANY)
        self.panel_3 = wx.Panel(self.p2, wx.ID_ANY)
        self.button1 = wx.Button(self.p2, wx.ID_OK, "")
        self.button2 = wx.Button(self.p2, 2, "Cancel")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.SpecifyDIR, self.button1)
        self.Bind(wx.EVT_BUTTON, self.Cancel, id=2)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: TemplateExporter.__set_properties
        self.SetTitle("Export Images")
        self.Filetype.SetSelection(0)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: TemplateExporter.__do_layout
        s0 = wx.BoxSizer(wx.HORIZONTAL)
        s1 = wx.BoxSizer(wx.VERTICAL)
        s2 = wx.BoxSizer(wx.HORIZONTAL)
        grid_s = wx.FlexGridSizer(4, 2, 0, 0)
        label1 = wx.StaticText(self.p1, wx.ID_ANY, "Format:")
        grid_s.Add(label1, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT | wx.ALL, 4)
        grid_s.Add(self.Filetype, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 4)
        label2 = wx.StaticText(self.p1, wx.ID_ANY, "Filename:")
        grid_s.Add(label2, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT | wx.ALL, 4)
        grid_s.Add(self.Filename, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 4)
        label3 = wx.StaticText(self.p1, wx.ID_ANY, "Start At:")
        grid_s.Add(label3, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT | wx.ALL, 4)
        grid_s.Add(self.StartID, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 4)
        label4 = wx.StaticText(self.p1, wx.ID_ANY, "Digits (1-8):")
        grid_s.Add(label4, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT | wx.ALL, 4)
        grid_s.Add(self.NumDigits, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 4)
        self.p1.SetSizer(grid_s)
        s1.Add(self.p1, 0, wx.EXPAND, 0)
        s2.Add(self.panel_3, 1, wx.EXPAND, 0)
        s2.Add(self.button1, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT | wx.ALL, 4)
        s2.Add(self.button2, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT | wx.ALL, 4)
        self.p2.SetSizer(s2)
        s1.Add(self.p2, 1, wx.EXPAND, 0)
        s0.Add(s1, 1, wx.EXPAND, 0)
        self.SetSizer(s0)
        s0.Fit(self)
        self.Layout()
        # end wxGlade

    def SpecifyDIR(self, event):  # wxGlade: TemplateExporter.<event_handler>
        print("Event handler 'SpecifyDIR' not implemented!")
        event.Skip()

    def Cancel(self, event):  # wxGlade: TemplateExporter.<event_handler>
        print("Event handler 'Cancel' not implemented!")
        event.Skip()

# end of class TemplateExporter

class MyApp(wx.App):
    def OnInit(self):
        self.frame = TemplateExporter(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
