#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.8.1 on Wed May 16 16:59:48 2018
#

import wx
import wx.grid

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        
        # Menu Bar
        self.frame_menubar = wx.MenuBar()
        wxglade_tmp_menu = wx.Menu()
        self.frame_menubar.Append(wxglade_tmp_menu, "File")
        self.SetMenuBar(self.frame_menubar)
        # Menu Bar end
        
        # Tool Bar
        self.frame_toolbar = wx.ToolBar(self, -1)
        self.SetToolBar(self.frame_toolbar)
        # Tool Bar end
        self.grid1 = wx.grid.Grid(self, wx.ID_ANY, size=(1, 1))
        self.ClearB1 = wx.Button(self, wx.ID_ANY, "Clear")
        self.grid2 = wx.grid.Grid(self, wx.ID_ANY, size=(1, 1))
        self.ClearB2 = wx.Button(self, wx.ID_ANY, "Clear")
        self.ExecuteB = wx.Button(self, wx.ID_ANY, "Execute")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle("frame")
        self.frame_toolbar.Realize()
        self.grid1.CreateGrid(10, 0)
        self.grid2.CreateGrid(10, 0)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        root = wx.BoxSizer(wx.VERTICAL)
        sizer1 = wx.BoxSizer(wx.HORIZONTAL)
        SizerC2 = wx.BoxSizer(wx.VERTICAL)
        SizerC1 = wx.BoxSizer(wx.VERTICAL)
        label1 = wx.StaticText(self, wx.ID_ANY, "Merge", style=wx.ALIGN_CENTER)
        SizerC1.Add(label1, 0, wx.ALIGN_CENTER | wx.ALL, 5)
        SizerC1.Add(self.grid1, 1, wx.EXPAND, 0)
        SizerC1.Add(self.ClearB1, 0, wx.ALIGN_CENTER | wx.ALL, 5)
        sizer1.Add(SizerC1, 1, wx.EXPAND, 0)
        label2 = wx.StaticText(self, wx.ID_ANY, "Split")
        SizerC2.Add(label2, 0, wx.ALIGN_CENTER | wx.ALL, 5)
        SizerC2.Add(self.grid2, 1, wx.EXPAND, 0)
        SizerC2.Add(self.ClearB2, 0, wx.ALIGN_CENTER | wx.ALL, 5)
        sizer1.Add(SizerC2, 1, wx.EXPAND, 0)
        root.Add(sizer1, 1, wx.EXPAND, 0)
        root.Add(self.ExecuteB, 0, wx.ALIGN_RIGHT | wx.ALL, 5)
        self.SetSizer(root)
        root.Fit(self)
        self.Layout()
        # end wxGlade

# end of class MyFrame

class MyApp(wx.App):
    def OnInit(self):
        self.frame = MyFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
